[brainflow]
git-tree-sha1 = "ecd0b9d9fcc5c0ab95df6372c6286b71f2967cdf"
lazy = true

    [[brainflow.download]]
    sha256 = "c6b4aeb48954286ad9570335d3edf08be1d383c5df7b5bb296ed08bbaba6a48e"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.6.0/compiled_libs.tar"
